# Generated by Django 4.2.7 on 2025-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, help_text='IP address, user_id, or API key', max_length=255)),
                ('endpoint', models.CharField(db_index=True, help_text='The API endpoint being accessed', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Request timestamp')),
            ],
            options={
                'verbose_name': 'Rate Limit Log',
                'verbose_name_plural': 'Rate Limit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['identifier', 'endpoint', 'timestamp'], name='limiter_rat_identif_ba2c6a_idx'), models.Index(fields=['identifier', 'timestamp'], name='limiter_rat_identif_e0f9c6_idx'), models.Index(fields=['endpoint', 'timestamp'], name='limiter_rat_endpoin_3e98cf_idx')],
            },
        ),
    ]
